In [1]:
import pickle
import numpy as np
import pandas as pd
import os
from snputils.genobj.snp.snpobj import SNPObject
from snputils.io.snp.read.vcf import VCFReader
from snputils.io.snp.write.vcf import VCFWriter

reader = VCFReader("/private/groups/ioannidislab/smeriglio/merged_vcfs/ancestry_EUR.vcf")

snpobj = reader.read()

print(snpobj.calldata_gt)

In [4]:
snpobj.calldata_gt = np.logical_not(snpobj.calldata_gt).astype(int)
print(snpobj.calldata_gt)

[[[0 0]
  [0 0]
  [0 0]
  ...
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ...
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ...
  [0 0]
  [0 0]
  [0 0]]

 ...

 [[0 0]
  [0 0]
  [0 0]
  ...
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ...
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ...
  [0 0]
  [0 0]
  [0 0]]]


In [ ]:
new_filename = '/private/groups/ioannidislab/smeriglio/trial/chr1/negative_ancestry_EUR.vcf'

vcf_writer = VCFWriter(snpobj, new_filename)
vcf_writer.write()