In [5]:
import pickle
import numpy as np
import pandas as pd
import os
from snputils.genobj.snp.snpobj import SNPObject
from snputils.io.snp.write.vcf import VCFWriter

num_chrom = 22

ancestry_map = {
 '0': 'AFR',
 '1': 'AHG',
 '2': 'EAS',
 '3': 'EUR',
 '4': 'NAT',
 '5': 'OCE',
 '6': 'SAS',
 '7': 'WAS'
}


for chrom_n in range(num_chrom):
    chrom_n+=1

    print(chrom_n)
    
    # read object
    pickle_file = "/private/groups/ioannidislab/smeriglio/pickle_files/lai_object_chr_" + str(chrom_n) + ".pkl"

    chrom = "chr" + str(chrom_n)

    chrom_folder = os.path.join("/private/groups/ioannidislab/smeriglio/vcf_files", chrom)

    if not os.path.exists(chrom_folder):
        os.mkdir(chrom_folder)


    with open(pickle_file, 'rb') as f:
        lai_object = pickle.load(f)

    #print(lai_object.physical_pos)

    pos_list = [f"{val1}_{val2}" for val1, val2 in lai_object.physical_pos]
    #print(pos_list)

    
    #iterate for each ancestry
    matches = []
    for ancestry in range(len(ancestry_map)):

        # modify the values to simulate a SNP file 
        match = (lai_object.lai == ancestry).astype(int)
        match = match.reshape(len(lai_object.lai),int(len(lai_object.lai[0])/2), 2 )

        matches.append(match)

    matches_array = np.array(matches)

    sum_matches = np.sum(matches_array, axis=0)

    match_test = np.ones(sum_matches.shape)

    if match_test != sum_matches:
        print(f"ERROR in chromosome {chrom_n}")
    

1


: 

In [1]:
import pickle
import numpy as np
import pandas as pd
import os
from snputils.genobj.snp.snpobj import SNPObject
from snputils.io.snp.write.vcf import VCFWriter

In [2]:
num_chrom = 1

ancestry_map = {
 '0': 'AFR',
 '1': 'AHG',
 '2': 'EAS',
 '3': 'EUR',
 '4': 'NAT',
 '5': 'OCE',
 '6': 'SAS',
 '7': 'WAS'
}

In [3]:
chrom_n = 1

print(chrom_n)
    
# read object
pickle_file = "/private/groups/ioannidislab/smeriglio/pickle_files/lai_object_chr_" + str(chrom_n) + ".pkl"

chrom = "chr" + str(chrom_n)

chrom_folder = os.path.join("/private/groups/ioannidislab/smeriglio/test", chrom)

if not os.path.exists(chrom_folder):
    os.mkdir(chrom_folder)


with open(pickle_file, 'rb') as f:
    lai_object = pickle.load(f)

1


In [4]:
lai_object.chromosome

array([1, 1, 1, ..., 1, 1, 1])

In [5]:
lai_object.lai.shape

(1871, 974818)

In [6]:
new_lai = lai_object.lai.reshape(len(lai_object.lai),int(len(lai_object.lai[0])/2), 2 )
new_lai.shape

(1871, 487409, 2)

In [9]:
print(new_lai[:,8325,1])

[7 7 7 ... 3 3 3]


In [10]:
# modify the values to simulate a SNP file 
match = (lai_object.lai == 3).astype(int)
match = match.reshape(len(lai_object.lai),int(len(lai_object.lai[0])/2), 2 )
print(match[:,8325,1])

[0 0 0 ... 1 1 1]


In [ ]:
pos_list = [f"{val1}_{val2}" for val1, val2 in lai_object.physical_pos]
    #print(pos_list)

In [ ]:
#iterate for each ancestry
for ancestry in range(len(ancestry_map)):

    # modify the values to simulate a SNP file 
    match = (lai_object.lai == ancestry).astype(int)
    match = match.reshape(len(lai_object.lai),int(len(lai_object.lai[0])/2), 2 )

    # create vcf object
    calldata_gt = match
    samples = np.array(lai_object.sample_IDs)
    variants_chrom = np.full(calldata_gt.shape[0], chrom, dtype='U5')
    variants_list = [str(i+1) for i in range(len(lai_object.window_size))]
    variants_id = np.array(variants_list)
    variants_ref = np.full(calldata_gt.shape[0], 'A', dtype='U5')
    variants_alt = np.full((calldata_gt.shape[0], 3), ['T', 'G', 'C'], dtype='U1')

    variant_data_obj = SNPObject(
        calldata_gt=calldata_gt,
        samples=samples,
        variants_chrom=variants_chrom,
        variants_id=variants_id,
        variants_ref = variants_ref,
        variants_alt = variants_alt,
        variants_pos = pos_list
    )

    # save ancestry data as vcf
    filename = 'ancestry_' + ancestry_map[str(ancestry)] + '.vcf'
    output_file = os.path.join(chrom_folder, filename) 
    vcf_writer = VCFWriter(variant_data_obj, output_file)
    print(output_file)

    vcf_writer.write()

In [4]:
import pickle
import numpy as np
import pandas as pd
import os
from snputils.genobj.snp.snpobj import SNPObject
from snputils.io.snp.write.vcf import VCFWriter

chrom_n = 1
print(chrom_n)

# read object
pickle_file = "/private/groups/ioannidislab/smeriglio/pickle_files/lai_object_chr_" + str(chrom_n) + ".pkl"

chrom = "chr" + str(chrom_n)

chrom_folder = os.path.join("/private/groups/ioannidislab/smeriglio/trial", chrom)

if not os.path.exists(chrom_folder):
    os.mkdir(chrom_folder)


with open(pickle_file, 'rb') as f:
    lai_object = pickle.load(f)

#print(lai_object.physical_pos)

pos_list = [val2 for val1, val2 in lai_object.physical_pos]
#print(pos_list)

1


In [5]:
print(pos_list)

[1092205, 1178925, 1210744, 1414070, 1537437, 1597020, 1619767, 1900186, 1921242, 1934647, 1966659, 2030977, 2215509, 2301471, 2338658, 2362827, 2802562, 2879460, 2889577, 3001848, 3062565, 3110735, 3148554, 3168338, 3264190, 3339339, 3404227, 3421586, 3457311, 3491107, 3517279, 3575929, 3601654, 3605508, 3681063, 3784276, 3835429, 4008061, 4010889, 4092563, 4108282, 4158955, 4283000, 4293138, 4367323, 4379687, 4508348, 4549380, 4673794, 4751995, 4770904, 4843233, 4900223, 5002457, 5032137, 5088994, 5130529, 5170712, 5227508, 5312690, 5358384, 5426757, 5534948, 5574895, 5636176, 5662664, 5710885, 5786651, 5886560, 5897070, 5917731, 6139169, 6144483, 6215713, 6324747, 6572271, 6640116, 6795230, 7021476, 7096700, 7170855, 7245019, 7372404, 7484011, 7511409, 7607204, 7694790, 7800342, 7904699, 7946009, 7965588, 8208246, 8274807, 8341333, 8981813, 8991116, 9002569, 9037230, 9067417, 9070184, 9224037, 9285639, 9364692, 9465727, 9542971, 9693275, 9714365, 9743729, 9889282, 9982387, 10234035,

In [2]:
ancestry = 3

# modify the values to simulate a SNP file 
match = (lai_object.lai == ancestry).astype(int)
match = match.reshape(len(lai_object.lai),int(len(lai_object.lai[0])/2), 2 )

# create vcf object
calldata_gt = match
samples = np.array(lai_object.sample_IDs)
variants_chrom = np.full(calldata_gt.shape[0], chrom, dtype='U5')
variants_list = [str(i+1) for i in range(len(lai_object.window_size))]
variants_id = np.array(variants_list)
variants_ref = np.full(calldata_gt.shape[0], 'A', dtype='U5')
variants_alt = np.full((calldata_gt.shape[0], 3), ['T', 'G', 'C'], dtype='U1')

variant_data_obj = SNPObject(
    calldata_gt=calldata_gt,
    samples=samples,
    variants_chrom=variants_chrom,
    variants_id=variants_id,
    variants_ref = variants_ref,
    variants_alt = variants_alt,
    variants_pos = pos_list
)



In [3]:
print(variant_data_obj.calldata_gt.shape)
print(variant_data_obj.calldata_gt[:,8325,1])

(1871, 487409, 2)


array([0, 0, 0, ..., 1, 1, 1])

In [6]:
# save ancestry data as vcf
filename = 'ancestry_' + 'EUR' + '.vcf'
output_file = os.path.join(chrom_folder, filename) 
vcf_writer = VCFWriter(variant_data_obj, output_file)
print(output_file)



/private/groups/ioannidislab/smeriglio/trial/chr1/ancestry_EUR.vcf


In [7]:
vcf_writer.write()

: 

In [2]:
import pickle
import numpy as np
import pandas as pd
import os
from snputils.genobj.snp.snpobj import SNPObject
from snputils.io.snp.write.vcf import VCFWriter

num_chrom = 1

ancestry_map = {
 '0': 'AFR',
 '1': 'AHG',
 '2': 'EAS',
 '3': 'EUR',
 '4': 'NAT',
 '5': 'OCE',
 '6': 'SAS',
 '7': 'WAS'
}


for chrom_n in range(num_chrom):
    chrom_n = 1

    print(f'starting chromosome {chrom_n}')
    
    # read object
    pickle_file = "/private/groups/ioannidislab/smeriglio/pickle_files/lai_object_chr_" + str(chrom_n) + ".pkl"

    chrom = "chr" + str(chrom_n)

    chrom_folder = os.path.join("/private/groups/ioannidislab/smeriglio/vcf_files", chrom)

    if not os.path.exists(chrom_folder):
        os.mkdir(chrom_folder)


    with open(pickle_file, 'rb') as f:
        lai_object = pickle.load(f)

    #print(lai_object.physical_pos)

    pos_list = [f"{val1}_{val2}" for val1, val2 in lai_object.physical_pos]
    #print(pos_list)

    
    #iterate for each ancestry
    matches = []
    for ancestry in range(len(ancestry_map)):

        # modify the values to simulate a SNP file 
        match = (lai_object.lai == ancestry).astype(int)
        match = match.reshape(len(lai_object.lai),int(len(lai_object.lai[0])/2), 2 )

        matches.append(match)
    
    print(f'finished production of matches for chrom: {chrom_n}')

    

starting chromosome 1


In [1]:
matches_array = np.array(matches)
sum_matches = np.sum(matches_array, axis=0)
print(sum_matches.shape)
print(match.shape)

NameError: name 'np' is not defined

In [6]:
import pickle
import numpy as np
import pandas as pd
import os
from snputils.genobj.snp.snpobj import SNPObject
from snputils.io.snp.read.vcf import VCFReader

reader = VCFReader("/private/groups/ioannidislab/smeriglio/trial/chr1/ancestry_EUR.vcf")

snpobj = reader.read()

print(snpobj.calldata_gt[:,8325,1])

/private/home/rsmerigl/anaconda3/envs/admixture/lib/python3.10/site-packages/allel/io/vcf_read.py:322: UserWarning: not all characters parsed for integer value; field: POS; variant: -1
  chunks = [d[0] for d in it]
/private/home/rsmerigl/anaconda3/envs/admixture/lib/python3.10/site-packages/allel/io/vcf_read.py:322: UserWarning: not all characters parsed for integer value; field: POS; variant: 0
  chunks = [d[0] for d in it]
/private/home/rsmerigl/anaconda3/envs/admixture/lib/python3.10/site-packages/allel/io/vcf_read.py:322: UserWarning: not all characters parsed for integer value; field: POS; variant: 1
  chunks = [d[0] for d in it]
/private/home/rsmerigl/anaconda3/envs/admixture/lib/python3.10/site-packages/allel/io/vcf_read.py:322: UserWarning: not all characters parsed for integer value; field: POS; variant: 2
  chunks = [d[0] for d in it]
/private/home/rsmerigl/anaconda3/envs/admixture/lib/python3.10/site-packages/allel/io/vcf_read.py:322: UserWarning: not all characters parsed f

[0 0 0 ... 1 1 1]


In [1]:
import pickle
import numpy as np
import pandas as pd
import os
from snputils.genobj.snp.snpobj import SNPObject
from snputils.io.snp.write.vcf import VCFWriter

chrom_n = 1
print(chrom_n)

# read object
pickle_file = "/private/groups/ioannidislab/smeriglio/pickle_files/lai_object_chr_" + str(chrom_n) + ".pkl"

chrom = "chr" + str(chrom_n)

chrom_folder = os.path.join("/private/groups/ioannidislab/smeriglio/trial", chrom)

if not os.path.exists(chrom_folder):
    os.mkdir(chrom_folder)


with open(pickle_file, 'rb') as f:
    lai_object = pickle.load(f)

1


In [2]:
lai_object.sample_IDs

['2502845',
 '2314965',
 '1142584',
 '3665122',
 '4377492',
 '2652670',
 '4015997',
 '2076736',
 '5587649',
 '1325300',
 '3944030',
 '5046164',
 '5410653',
 '1432157',
 '1224542',
 '3525397',
 '2850227',
 '6005744',
 '3946352',
 '4540525',
 '1046029',
 '1263928',
 '3825840',
 '3093739',
 '5403487',
 '3073546',
 '2604422',
 '2307991',
 '3479525',
 '5087046',
 '4818669',
 '2063443',
 '1337395',
 '4144793',
 '1907638',
 '1178823',
 '1643177',
 '1680391',
 '5156560',
 '2250987',
 '1698996',
 '4132961',
 '2191453',
 '3671334',
 '3828605',
 '5537948',
 '5721658',
 '4361407',
 '3539607',
 '2153403',
 '5249252',
 '3295136',
 '3575489',
 '1225338',
 '3738985',
 '2986713',
 '5650938',
 '3047274',
 '1759996',
 '2788800',
 '5958661',
 '2704944',
 '1276731',
 '5750428',
 '4085443',
 '2309008',
 '4074681',
 '4315048',
 '1457628',
 '5873991',
 '2892098',
 '1603412',
 '4043982',
 '4876155',
 '2735732',
 '5013764',
 '5069142',
 '4117369',
 '3742073',
 '1090467',
 '4420155',
 '5888846',
 '2445593',
 '38

In [3]:
import pickle
import numpy as np
import pandas as pd
import os
from snputils.genobj.snp.snpobj import SNPObject
from snputils.io.snp.write.vcf import VCFWriter

chrom_n = 1
print(chrom_n)

# read object
pickle_file = "/private/groups/ioannidislab/smeriglio/pickle_files/lai_object_chr_" + str(chrom_n) + ".pkl"

chrom = "chr" + str(chrom_n)

chrom_folder = os.path.join("/private/groups/ioannidislab/smeriglio/trial", chrom)

if not os.path.exists(chrom_folder):
    os.mkdir(chrom_folder)


with open(pickle_file, 'rb') as f:
    lai_object = pickle.load(f)

lai_object.sample_IDs = ['2502845',
 '2314965', '3516803']

#print(lai_object.physical_pos)

pos_list = [val2 for val1, val2 in lai_object.physical_pos]
#print(pos_list)

ancestry = 3

# modify the values to simulate a SNP file 
match = (lai_object.lai == ancestry).astype(int)
match = match.reshape(len(lai_object.lai),int(len(lai_object.lai[0])/2), 2 )
match = match[:,[0,1,8325],:]

print(match[:,2,1])

1
[0 0 0 ... 1 1 1]


In [8]:
import pickle
import numpy as np
import pandas as pd
import os
from snputils.genobj.snp.snpobj import SNPObject
from snputils.io.snp.write.vcf import VCFWriter

chrom_n = 1
print(chrom_n)

# read object
pickle_file = "/private/groups/ioannidislab/smeriglio/pickle_files/lai_object_chr_" + str(chrom_n) + ".pkl"

chrom = "chr" + str(chrom_n)

chrom_folder = os.path.join("/private/groups/ioannidislab/smeriglio/trial", chrom)

if not os.path.exists(chrom_folder):
    os.mkdir(chrom_folder)


with open(pickle_file, 'rb') as f:
    lai_object = pickle.load(f)

lai_object.sample_IDs = ['2502845',
 '2314965', '3516803']

#print(lai_object.physical_pos)

pos_list = [val2 for val1, val2 in lai_object.physical_pos]
#print(pos_list)

ancestry = 3

# modify the values to simulate a SNP file 
match = (lai_object.lai == ancestry).astype(int)
match = match.reshape(len(lai_object.lai),int(len(lai_object.lai[0])/2), 2 )
match = match[:,[0,1,8325],:]

# create vcf object
calldata_gt = match
samples = np.array(lai_object.sample_IDs)
variants_chrom = np.full(calldata_gt.shape[0], chrom, dtype='U5')
variants_list = [str(i+1) for i in range(len(lai_object.window_size))]
variants_id = np.array(variants_list)
variants_ref = np.full(calldata_gt.shape[0], 'A', dtype='U5')
variants_alt = np.full((calldata_gt.shape[0], 3), ['T', 'G', 'C'], dtype='U1')
qual = np.full(variants_id.shape, 100)

variant_data_obj = SNPObject(
    calldata_gt=calldata_gt,
    samples=samples,
    variants_chrom=variants_chrom,
    variants_id=variants_id,
    variants_ref = variants_ref,
    variants_alt = variants_alt,
    variants_pos = pos_list,
    variants_qual = qual
)

#(variant_data_obj.calldata_gt.shape)
#print(variant_data_obj.calldata_gt[:,8325,1])

# save ancestry data as vcf
filename = 'ancestry_' + 'EUR' + '_3samples.vcf'
output_file = os.path.join(chrom_folder, filename) 
vcf_writer = VCFWriter(variant_data_obj, output_file)
print(output_file)

vcf_writer.write()

1


/private/groups/ioannidislab/smeriglio/trial/chr1/ancestry_EUR_3samples.vcf
